apiVersion: v1
kind: Secret
metadata:
  name: quang-readonly-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: quang-readonly
type: kubernetes.io/service-account-token
