apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: quang-readonly-binding
subjects:
- kind: ServiceAccount
  name: quang-readonly
  namespace: default
roleRef:
  kind: ClusterRole
  name: quang-readonly-role
  apiGroup: rbac.authorization.k8s.io
