apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: quang-admin-binding
  namespace: quang26
subjects:
- kind: ServiceAccount
  name: quang-admin
  namespace: quang26
roleRef:
  kind: Role
  name: quang-admin-role
  apiGroup: rbac.authorization.k8s.io
