apiVersion: v1
kind: Secret
metadata:
  name: test-secret-default
  namespace: default
type: Opaque
stringData:
  password: secret123
---
apiVersion: v1
kind: Secret
metadata:
  name: test-secret-quang26
  namespace: quang26
type: Opaque
stringData:
  password: supersecret456
