apiVersion: v1
kind: Pod
metadata:
  name: test-pod-default
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-quang26
  namespace: quang26
spec:
  containers:
  - name: nginx
    image: nginx:alpine
